.TH PMAN 1 "2011" "The PHP Documentation Team" "Manual pager utils"
.\" Please adjust this date whenever revising the manpage.
.\" for manpage-specific macros, see man(7)
.SH NAME
pman \- an interface to the online reference manuals
.SH SYNOPSIS
.B pman
.RI [ function|variable|classname.method|wrapper: ]

.SH DESCRIPTION
.B pman
is an quickish utility that accesses the Unix manpages for the PHP manual.


.SH OPTIONS
None

.SH SEE ALSO
.BR phd (1),
.BR man (1),
.SH AUTHOR
pman, and its manual pages, was written by <The PHP Documentation Team>

